@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml



title Component diagram for visa application system

System_Ext(globalVisaDataHubSystem, "Global Visa Data Hub System", "An external system that manages visa information from various countries. Providing real-time updates and handling visa applications to relevant countries")

Container_Boundary(frontend, "frontend") {
    Container_Boundary(UI, "Browser") {

    }
    Container_Boundary(presentation, "Presentation") {
        Component(Authentication, "Authentication", "JWT", "Uses JWT to check if device is authorized to access certain routes")

        Container_Boundary(routes, "Routes"){
            
        }
    }
}

Container_Boundary(backend, "Backend Server Side") {
    Container_Boundary(api, "Api Layer") {
            Component(authApi, "Auth Controller", "Rest Controller", "Allow users to create accounts and login to the system")
            Component(visaApi, "Visa Controller", "Rest Controller", "Allow users get sugestions for visas and find visa information via an external system")
        Component(applicationApi, "Visa Application Controller", "Rest Controller", "Allow visa applicants to create their visa applications, submit, save & resume and include additional information to visa")
       ' Component(appointmentApi, "Appointment Controller", "Rest Controller", "Allow visa applicants the ability to book an appointment and view appointment data")
       ' Component(ticketApi, "ticket surport Controller", "Rest Controller", "Allow Visa applicants & visa officers the ability to create surport tickets")
    }
    Container_Boundary(application, "Application Layer") {
         Component(registrationService, "registration service", "CQRS Service", "handles registation processors")
         Component(loginService, "login service", "CQRS service", "allow users to sign into the application and applies security checks")
    
        Component(suggestionService, "Suggestion service", "CQRS service", "allow visa applicant to get a visa suggestion from the system")
        Component(findVisasService, "Find Visa's service", "CQRS service", "allow users to find all visas accossiated to a country")
        Component(findVisaService, "Find Visa service", "CQRS service", "allow users to find information regarding a specfic type of visa")
    }

    Container_Boundary(infrastructure, "infrastructure Layer") {
        Component(visaRepo, "Visa Repository", "", "handles interactions to the external visa application")
        Component(userRepo, "User Repository", "", "handles interactions to the User database container") 
        Component(applicationRepo, "Visa Application Repository", "", "handles interactions to the application database container")
        'Component(appointmentRepo, "Appointment Repository", "", "handles interactions to the appointment database container")
        'Component(ticketRepo, "Ticket Surport Repository", "", "handles interactions to the ticket surport database container")
    }

    Container_Boundary(domain, "Domain Layer") {

    }

    Rel_D(api, application, "3")
    Rel_D(application, domain , "4")

}

Rel_D(UI, presentation, "1. Loads")
Rel_D(presentation, api, "2. make api calls")


Rel_L(visaRepo, globalVisaDataHubSystem, "Uses to get visa suggestions and information" )



SHOW_LEGEND()

@enduml