@startuml "System Context"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

SHOW_PERSON_OUTLINE()

title <size:40> System Context Diagram
caption "This system context diagram aims to provide a high level overview of the system. Show casing the users that use the system and the external systems that we use within the system. it serves as a valueable artifact to show to both technical and non-technical memebers"
Person(anonymousUser, Anonymous User, "An unauthorised client who has not yet gained access to the sy")
Person(visaApplicant, Visa Applicant, "An user who intends to find information regarding visas and submit a visa application")
Person(visaOfficer, Visa Processor, "A user who works for a branch and supports visa applications and reviews applications before submission to third party country")
Person(supportSpecialist, Support Specialist , "A user who handles customer support and technical support to both customers of the system but also members of staff.")
Person(branchManager, Branch Manager, "An user who has control over a local branch and the customer support working at the branch. With the ability to add visa processors")
Person(admin, Admin, "A user who has control over user privileges and data. -adding more branches and branch managers to the system")
System(processingSystem, "Visa Processing System", "Allows users to get visa informations and submit visa applcations to be reviewed")
System_Ext(globalVisaDataHubSystem, "Global Visa Data Hub System", "An external system that manages visa information from various countries. Providing real-time updates and handling visa applications to relevant countries ")

Rel_D(anonymousUser, processingSystem, "Signs up/ logins to the system")
Rel_D(visaApplicant, processingSystem, "Requests visa suggestions, Finds & Views visa information, Create, View, Save & Resume visa applications, Schedule and view biometric appointments, Create and View Support Tickets")
Rel_D(visaOfficer, processingSystem, "Reviews and validates visa applications, Requests Further Information For Applications, Manages Visa Applicant Appointments Assists with providing Biometric identification, Creates And Views Support Tickets")
Rel_D(supportSpecialist, processingSystem, "Reviews and Replies To Support Tickets")
Rel_D(branchManager, processingSystem, "Manages Branch Employees(VisaProcessors & SupportSpecialists), Assign Appointments To Visa Processors")
Rel_D(admin, processingSystem, "Manages Branches, Manages Branch Management")
Rel_D(processingSystem, globalVisaDataHubSystem, "Get Visa information and sends reviewed applications to the system to be directed to the correct country via api's")

SHOW_LEGEND() 
@enduml