@startuml "messagebus"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("storage", $shape=RoundedBoxShape(), $bgColor="lightSkyBlue", $fontColor="white")
AddElementTag("noSqlContainer", $shape=RoundedBoxShape(), $bgColor="DarkBlue", $fontColor="white")


SHOW_PERSON_OUTLINE()

title <size:40> Container Diagram

Person(anonymousUser, Anonymous User, "An unauthorized client who has not yet gained access to the system")
Person(visaApplicant, Visa Applicant, "A user who intends to find information regarding visas and submit a visa application")
Person(visaOfficer, Visa Processor, "A AFS employee who works for a branch and supports visa applications and reviews applications before submission to third-party countries")
Person(supportSpecialist, Support Specialist, "A AFS employee who handles customer support and technical support to both customers of the system and members of staff.")
Person(branchManager, Branch Manager, "A AFS employee who has control over a local branch and the customer support working at the branch. With the ability to add visa processors")
Person(admin, Admin, "A AFS employee who has control over user privileges and data - adding more branches and branch managers to the system")

System_Ext(globalVisaDataHubSystem, "Global Visa Data Hub System", "An external system that manages visa information from various countries. Providing real-time updates and handling visa applications to relevant countries")

System_Boundary(c1, "Visa Application System") {
    Container(userInterface,"User Interface" ,"Browser", "Renders the frontend")
    Container(frontend, "Presentation Layer (Responsive)", "Blazor", "Provides the frontend interface which is responsive for mobile and web")
    Container(api, "API", "HTTP", "Processess requests made from the frontend and returns a result")
    Container(application, "Application Layer", "C#", "retrieves the command from the API and processes and validates using command handing (CQRS). this layer is containing all core logic")
    Container(domain, "Domain Layer", "C#", "Encapsulates the core bussiness logic")
    Container(infrastructure, "Infrastructure Layer", "C#", "Handles Data access allowing for reading and writing to the database. Logging will occur here")
    ContainerDb(cosmos_db, "CosmosDb", , "Stores user accounts, visa applications, appointments, and branch data", $tags = "storage")
}

Rel_D(anonymousUser, userInterface, "Signs up/ logins to the system")
Rel_D(visaApplicant, userInterface, "Requests visa suggestions, Finds & Views visa information, Create, View, Save & Resume visa applications, Schedule and view biometric appointments, Create and View Support Tickets")
Rel_D(visaOfficer, userInterface, "Reviews and validates visa applications, Requests Further Information For Applications, Manages Visa Applicant Appointments Assists with providing Biometric identification, Creates And Views Support Tickets")
Rel_D(supportSpecialist, userInterface, "Reviews and Replies To Support Tickets")
Rel_D(branchManager, userInterface, "Manages Branch Employees(VisaProcessors & SupportSpecialists), Assign Appointments To Visa Processors")
Rel_D(admin, userInterface, "Manages Branches, Manages Branch Management")

Rel_D(userInterface, frontend, "renders the presentation layer")
Rel_D(frontend, api, "Calls the api")
Rel_D(api, application, "handles")
Rel_D(application, domain, "uses")
Rel_D(domain, infrastructure, "Uses dependancy injection to gain access to database")
Rel_L(infrastructure, cosmos_db , "Gets and stores user accounts, visa applications, branch data, and meeting schedules")
Rel_R(api, globalVisaDataHubSystem, "Get Visa information and sends reviewed applications to the system to be directed to the correct country")

Rel_U(userInterface, frontend, "renders the presentation layer")
Rel_U(frontend, api, "Calls the api")
Rel_U(api, application, "handles")
Rel_U(application, domain, "uses")
Rel_U(domain, infrastructure, "Uses dependancy injection to gain access to database")
Rel_R(infrastructure, cosmos_db , "Gets and stores user accounts, visa applications, branch data, and meeting schedules")
Rel_L(api, globalVisaDataHubSystem, "Get Visa information and sends reviewed applications to the system to be directed to the correct country")
SHOW_LEGEND()
@enduml