@startuml
title <size:40> Domain Model

abstract class User{
first name
last name
email
dob
password
role
}

class VisaApplicant{

}

class VisaProcessor{

}

class SupportSpecalist{

}

class BranchManager{

}

class Admin{

}

enum Role{
Visa applicant
Support Specalist
Branch manager
admin
visa proccessor
}

VisaApplicant --|> User : Extends
VisaProcessor --|> User : Extends
BranchManager --|> User : Extends
Admin --|> User : Extends
SupportSpecalist--|> User : Extends
User *-- Role : "Has a"


Admin --> BranchManager  : creates
Admin --> Branch  : creates  


BranchManager --> VisaProcessor: Creates
BranchManager --> SupportSpecalist: Creates

class Appointment{
}

class Schedule{

}

Schedule "1" o-  "*" Appointment: "has"
Appointment "*" *-- "1" VisaApplicant : "Books a"

class Application {

}

class Address{
Street
Postcode
}

class ApplicationChat{

}

class PersonalDetails{

}

class TravelDetails{

}

class Document{

}

class BiometricIdentification{

}

class Passport{

}


enum status{
Pending
Need more information
approved
declined
}

Application *-- status : "Has"
Application "1"  *-- "1" PersonalDetails : "Has"
Application "1" *-- "1" TravelDetails : "Has"
Application "1"  *-- "*" Passport : "Has"
Application "1"  *-- "*" Document : "Has"
Application "1"  *-- "0..1" BiometricIdentification : "Could Have"
Application "1" *-- "1" ApplicationChat : "Has"
PersonalDetails "1" *-- "1" Address : "Has"

class VisaSuggestion{

}

class FindVisa{

}

class Visa{

}

Class VisaDocumentation{

}

class VisaEligibility {

}

class VisaInformation {

}
VisaProcessor -- FindVisa: "uses"
VisaApplicant -- FindVisa: "uses"
VisaApplicant -- VisaSuggestion : "Requests"
VisaApplicant "1"  -- "*" Application : "submits a"
VisaSuggestion -- Visa : "gets"
FindVisa -- Visa : "gets"
Visa "1" *-- "1" VisaDocumentation : "Has"
Visa "1" *-- "1" VisaEligibility : "Has"
Visa "1" *-- "1" VisaInformation : "Has"

class Branch{

}

class OpeningTimes{
Open
Close
}

Enum Days{
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
}

Branch "1" *-- "1" OpeningTimes : "Has"
OpeningTimes "1" *-- "7" Days : "Has"
BranchManager "1" o-- "1" Branch : "Has a"

VisaProcessor "0..1" -- "*" Application : "Reviews"
VisaProcessor "1" --  "1" Schedule: "Views"

class Ticket{

}

VisaProcessor "*" -- "1" Ticket : "Creates"
VisaApplicant "*" -- "1" Ticket : "Creates"
SupportSpecalist "*" -- "1" Ticket : "Views and responds"

note top of User: Users implements User interface

note "Users submit information for a suggestion and is given a visa object with its child objects" as N1
Visa.. N1
N1 .. VisaSuggestion

note left of Visa: Details from api

note bottom of Role: Contains all user roles
@enduml