@startuml
title <size:40> Domain Model

abstract class User{
first name
last name
email
dob
password
role
}

class VisaApplicant{

}

class VisaFacilitator{

}

class VisaProcessor{

}

class SupportSpecalist{

}

class BranchManager{

}

class Admin{

}

enum Role{
Visa applicant
Support Specalist
Branch manager
admin
visa proccessor
}

VisaApplicant --|> User : Extends
VisaProcessor --|> User : Extends
BranchManager --|> User : Extends
Admin --|> User : Extends
SupportSpecalist--|> User : Extends
VisaApplicant <|-- VisaFacilitator : Extends
User *-- Role : "Has a"


Admin --> BranchManager  : creates
Admin --> Branch  : creates  
Admin --> SupportSpecalist: creates 

BranchManager --> VisaProcessor: Creates

class Appointment{
Reason
DateTime
Branch Location
}

class Schedule{

}

Schedule "1" o-  "*" Appointment: "has"
Appointment "*" *-- "1" VisaApplicant : "Books a"

class BulkApplication{

}

class Application {
submisson date
last updated
assigned
}

class Address{
Street
Postcode
}

class ApplicationChat{

}

class PersonalDetails{

}

class TravelDetails{

}

class Document{

}

class BiometricIdentification{

}


enum status{
Pending
Need more information
approved
declined
}

Application *-- status : "Has"
Application "1"  *-- "1" PersonalDetails : "Has"
Application "1" *-- "1" TravelDetails : "Has"
Application "1"  *-- "*" Document : "Has"
Application "1"  *-- "0..1" BiometricIdentification : "Could Have"
Application "1" *-- "1" ApplicationChat : "Has"
PersonalDetails "1" *-- "1" Address : "Has"
Application "1..*" o-- BulkApplication : "submits"
VisaFacilitator -- BulkApplication 
class VisaSuggestion{

}

class Visa{

}

Class VisaDocumentation{

}

class VisaEligibility {

}

class VisaInformation {

}

VisaApplicant -- VisaSuggestion : "Requests"
VisaApplicant "1"  -- "*" Application : "submits a"
VisaSuggestion -- Visa : "gets"
Visa "1" *-- "1" VisaDocumentation : "Has"
Visa "1" *-- "1" VisaEligibility : "Has"
Visa "1" *-- "1" VisaInformation : "Has"

class Branch{
Reason
DateTime
Branch Location
}

class OpeningTimes{
Open
Close
}

Enum Days{
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
}

Branch "1" *-- "1" OpeningTimes : "Has"
OpeningTimes "1" *-- "7" Days : "Has"
BranchManager "1" o-- "1" Branch : "Has a"

VisaFacilitator -- VisaSuggestion
VisaFacilitator "1" -- "*" Application : "submits a"
VisaProcessor "0..1" -- "*" Application : "Reviews"
VisaProcessor "1" --  "1" Schedule: "Views"


package "Customer Surport Chat & Visa Application" #DDDDDD {
  Conversation "1" -- "1..." Message
}

User "*" -- "1" Conversation : "get surport"
SupportSpecalist "*" -- "1" Conversation : "Helps the user"

note top of User: Users implements User interface

note "Users submit information for a suggestion and is given a visa object with its child objects" as N1
Visa.. N1
N1 .. VisaSuggestion

note left of Visa: Details from api

note bottom of BulkApplication: Ability to apply for multiple visas at a time

note bottom of Role: Contains all user roles
@enduml