@startuml

title Find Countries Visas And Select To Find More Information UC005

actor "Visa Applicant" as VisaApplicant

box "Visa Processing System" #LightBlue
    participant "Browser" as Browser
    participant "Presentation Layer [Blazor]" as Presentation
    participant "API Layer" as ApiLayer  
    participant "Application Layer" as Application
    participant "Domain Layer" as Domain
    participant "Infrastructure" as Infrastructure  
    participant "User Database" as External

    VisaApplicant -> Browser: Load Application Page
    activate Browser

    Browser -> Presentation: Load Blazor Component
    activate Presentation

    Presentation --> VisaApplicant: Render Auth Login Page

    VisaApplicant -> Presentation: send LoginData(username, password)

    Presentation -> ApiLayer  : GET + /Auth/Login?username = UsernameValue&password = PasswordValue
    activate ApiLayer  

    ApiLayer   -> Application: Handle.Handlelogin(login)
    activate Application

    Application -> Infrastructure  : UserRepository.GetUserAsync(email)
    activate Infrastructure  

    Infrastructure   -> External: requests the user information
    activate External

    External --> Infrastructure  : gets user details
    deactivate External

    group Error
    External --> Infrastructure: 404 could not find user
    end

    Infrastructure   --> Application: returns user to application layer
    deactivate Infrastructure   

    Application --> ApiLayer  : compares hashed passwords and returns a jwt token
    deactivate Application

    ApiLayer   --> Presentation: Return 200 with JWT in response Body and authen
    deactivate ApiLayer   

    Presentation --> VisaApplicant: authenticates the user
end box
@enduml
