@startuml

title Visa Suggestion & View Suggestion US003/US004

actor "Visa Applicant" as VisaApplicant

box "Visa Processing System" #LightBlue
    participant "Browser" as Browser
    participant "Presentation Layer [Blazor]" as Presentation
    participant "API Layer" as ApiLayer
    participant "Application Layer" as Application
    participant "Domain Layer" as Domain
    participant "Infrastructure" as Infrastructure
    participant "Global Visa Data Hub External System" as External

    VisaApplicant -> Browser: Load Application Page
    activate Browser

    Browser -> Presentation : Load Blazor Component
    activate Presentation

    Presentation --> VisaApplicant: [user.Identity.IsAuthenticated & UserRole = "Visa Applicant"] Render Home-Page with suggestion wizzard

VisaApplicant -> Presentation: VisaSuggestion(Destination, Travel, CountryOfOrgin)

group information
Presentation --> VisaApplicant : Render message informing user to enter all required information
end

Presentation -> ApiLayer : [UserRole = "Visa Applicant"] Call Visa Controller and pass suggestion data
activate ApiLayer 

ApiLayer -> Application : Handle.SuggestionService(VisaSuggestion)
activate Application

Application -> Domain : ValidateSuggestion()
activate Domain 

group information
Domain --> VisaApplicant : Validation Failied, return 400 code and inform the user why
end

Domain --> Application : Verifed Request
Deactivate Domain

Application -> Infrastructure: VisaIntegrationService.GetSuggestion(VisaSuggestion)
  activate Infrastructure

Infrastructure -> External : Calls external api and passes data 
activate External

group Error
External --> VisaApplicant : 503 Service is not available, display error message
end

group Error
External --> VisaApplicant : 404 could not find/generate suggestion based on data provided.
end

External --> Infrastructure : returns json response
deactivate External

Infrastructure --> Domain : Map to Visa Domain Model - Map.VisaSuggestion(Response)
activate Domain

Domain --> Infrastructure : Return Visa Domain Model
deactivate Domain

Infrastructure --> Application : return Visa 
deactivate Infrastructure 

Application --> ApiLayer : return Visa 
deactivate Application

ApiLayer --> Presentation : Return 200 with Visa in response Body
deactivate ApiLayer 

Presentation --> VisaApplicant: Render Visa Suggestion
note bottom
    User has the following options when on this page "Visa Overview, Eligibility, Documentation and the option to apply for a application"
end note
VisaApplicant -> Presentation: Click Eligibility Tab
Presentation --> VisaApplicant: Render Eligibility Information

VisaApplicant -> Presentation: Click Documentation Tab
Presentation --> VisaApplicant: Render Documentation infromation
deactivate VisaApplicant 
deactivate Presentation
deactivate Browser 
end box

@enduml